# Copyright (C) SchedMD LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.disk :disk, size: "16GB", primary: true

  # Ubuntu 20.04 LTS
  config.vm.define "ubuntu2004" do |ubuntu2004|
    ubuntu2004.vm.box = "generic/ubuntu2004"
  end

  # Debian 10
  config.vm.define "debian10" do |debian10|
    debian10.vm.box = "generic/debian10"
  end

  # CentOS 7
  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "generic/centos7"
  end

  # RHEL 7
  config.vm.define "rhel7" do |rhel7|
    config.vm.box = "generic/rhel7"
  end

  # CentOS 8
  config.vm.define "centos8" do |centos8|
    centos8.vm.box = "generic/centos8"
  end

  # RHEL 8
  config.vm.define "rhel8" do |rhel8|
    config.vm.box = "generic/rhel8"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbook.yml"
    ansible.galaxy_role_file = "./requirements.yml"
    ansible.galaxy_roles_path = "./roles_galaxy"
  end
end
